# Generated by Django 3.1.6 on 2021-02-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='profilepic/')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('primary_phone', models.CharField(max_length=12)),
                ('secondary_phone', models.CharField(blank=True, max_length=12, null=True)),
                ('address', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('bachelor_from', models.CharField(blank=True, max_length=250, null=True)),
                ('masters_from', models.CharField(blank=True, max_length=250, null=True)),
                ('certificates', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='resume/')),
            ],
        ),
    ]
