# Generated by Django 3.1.3 on 2021-02-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210208_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='profiile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_age', models.CharField(max_length=100)),
            ],
        ),
    ]
