# Generated by Django 3.1.3 on 2021-02-11 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_profiile'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=120)),
                ('user_name', models.CharField(max_length=100)),
                ('user_age', models.CharField(max_length=100)),
                ('user_eamil', models.EmailField(max_length=254)),
                ('user_phone', models.IntegerField(max_length=13)),
                ('user_profession', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='profiile',
        ),
    ]
