# Generated by Django 3.1.3 on 2021-02-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20210211_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_phone',
            field=models.IntegerField(),
        ),
    ]
